---
title: "Referencias de la tercera sesión"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Algunas referencias de cosas útiles:

1. Hablamos de las funciones [join](http://stat545.com/bit001_dplyr-cheatsheet.html#left_joinsuperheroes-publishers) de la librería *dplyr*. [Aquí](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf) pueden ver algunas funciones para manejo de datos (también incluye detalles de *tidyr*).
2. Mencionamos unos [gráficos de correlaciones](https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html) que se pueden hacer con el paquete *corrplot*.
3. Les hablé muy brevemente de gramática de gráficas. En [este](http://vita.had.co.nz/papers/layered-grammar.pdf) paper explican muy claramente el concepto, como se pensó al implementarlo en el paquete [*ggplot2*](http://ggplot2.org/). 
4. Si quieren empezar a jugar con gráficas, les recomiendo ver este [tutorial](http://tutorials.iq.harvard.edu/R/Rgraphics/Rgraphics.html), y revisar la [cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf).
5. Ya pueden encontrar el [script](https://github.com/monzalo14/aprendeR/blob/master/02_manipulacion/ejemplos_dplyr.R) con los ejemplos que usamos hoy en la carpeta de la unidad 2, en el que platicamos de la utilidad del verbo *arrange()*, combinado con *group_by()*.

¿Dudas? ¿Comentarios? [Escríbanme](mailto:monzalo14@gmail.com)
