#Github

##¿Qué es Github?

GitHub es una plataforma para alojar proyectos que utiliza el sistema de control de versiones git.

Aunque es la más popular, no es la unica. Existen otras plataformas como BitBucket que también permiten realizar tareas similares.

### Entonces... ¿Qué es Git?

* Git es un sistema de control de versiones que sirve para dar seguimiento a los cambios en los archivos de una computadora y coordinar el trabajo de esos archivos entre multiples personas. 

* Principalmente es usado para el desarrollo de software, aunque puede ser usado para mantener un seguimiento de cualquier archivo.

* Git fue creado en el año 2005 por Linus Torvalds (Sí, por él Linux tiene ese nombre) para coordinal el desarrollo del kernel Linux.

## ¿Por qué usar Github?

* Versionar tu código
* Aprender y experimentar
* Contribuir
* Trabajo en equipo
* Estar informado(a)
* Visor de código
* Mostrar tus conocimientos
* Registro de incidencias
* Compatibilidad
* Precio (Es gratis para repositorios públicos)

*Para una mayor exposición de cada punto https://gist.github.com/equintana/57a55dfb0337f5cd15cd*

## Instalación

En esta página puedes encontrar todo lo referente a la instalación de git sin importar cual sea tu sistema operativo.  
*https://git-scm.com/downloads*


### Linux

####Debian
```bash
$ sudo apt install git
```

####Fedora 
```bash
$ yum install git-core
```

### Windows

[Aqui](https://git-for-windows.github.io/) puedes ver lo que tienes que hacer para tener git en Windows.


### Mac

Hay dos formas de instalarlo:

1. [Via el instalador git](http://code.google.com/p/git-osx-installer)
2. Con [MacPorts](http://www.macports.org) instalado:

```bash
$ sudo port install git-core +svn +doc +bash_completion +gitweb
```


##Diferencia entre repo local y repo remoto
Image de comparación entre archivo modificado y sin modificasr.

##Comandos básicos

- git clone
- git add
- git status
- git pull
- git push
